config/routes.rb
# frozen_string_literal: true

class Blacklist
  def matches?(request)
    !BannedIp.exists? ip: request.remote_ip
  end
end

Catarse::Application.routes.draw do
  constraints Blacklist.new do
    mount RedactorRails::Engine => '/redactor_rails'
    mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
    devise_for(
      :users,
      {
        path: '',
        path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
        controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords, sessions: :sessions }
      }
    )

    devise_scope :user do
      post '/sign_up', { to: 'devise/registrations#create', as: :sign_up }
      get '/not-my-account', to: 'sessions#destroy_and_redirect', as: :not_my_account
    end

    # User permalink profile
    constraints SubdomainConstraint do
      get '/', to: 'users#show'
    end

    get '/amigos' => redirect('http://crowdfunding.catarse.me/amigos')
    get '/criadores' => redirect('http://crowdfunding.catarse.me/criadores')
    get '/paratodos' => redirect('http://crowdfunding.catarse.me/paratodos')

    get '/support_forum' => 'zendesk_sessions#create', as: :zendesk_session_create
    get '/posts' => 'application#get_blog_posts'
    get '/project_edit' => 'application#redirect_to_last_edit'
    get '/billing_edit' => 'application#redirect_to_user_billing'
    get '/user_contributions' => 'application#redirect_to_user_contributions'
    post '/subscribe_newsletter' => 'mail_marketing_users#subscribe'
    get '/unsubscribe_list' => 'mail_marketing_users#unsubscribe'

    get '/thank_you' => 'static#thank_you'
    get '/follow-fb-friends' => 'users#follow_fb_friends', as: :follow_fb_friends
    get '/connect-facebook' => 'application#connect_facebook', as: :connect_fb

    get '/notifications/:notification_type/:notification_id' => 'notifications#show'

    filter :locale, exclude: /\/auth\//

    mount CatarsePagarme::Engine => '/', as: :catarse_pagarme
    # mount CatarseWepay::Engine => "/", as: :catarse_wepay
    mount Dbhero::Engine => '/dbhero', as: :dbhero

    resources :categories, only: [] do
      member do
        get :subscribe, to: 'categories/subscriptions#create'
        get :unsubscribe, to: 'categories/subscriptions#destroy'
      end
    end
    resources :auto_complete_projects, only: [:index]
    resources :auto_complete_cities, only: [:index]
    resources :rewards, only: [] do
      resources :surveys, only: [:create, :update], controller: 'surveys'
    end
    resources :projects, path: '/', only: [:index]
    resources :flexible_projects, path: '/', controller: 'projects', only: [:index]
    # @TODO update links, we don't need this anymore
    resources :flexible_projects, controller: 'projects', except: [:index] do
      member do
        get :publish
        get :push_to_online
        get :validate_publish
        get :finish
      end
    end
    resources :contributions, only: [] do
      resources :surveys, only: [:show], controller: 'surveys' do
        member do
          put :answer
        end
      end
    end
    resources :projects, only: %i[create update edit new show] do
      resources :accounts, only: %i[create update]
      resources :posts, controller: 'projects/posts', only: %i[destroy show create]
      resources :rewards do
        member do
          get :toggle_survey_finish
        end
        resources :surveys, only: [:new], controller: 'surveys'
        post :sort, on: :member
      end
      resources :contributions, { except: [:index], controller: 'projects/contributions' } do
        collection do
          get :fallback_create, to: 'projects/contributions#create'
          put :update_status
        end
        member do
          get 'toggle_anonymous'
          get 'toggle_delivery'
          get :second_slip
          get :receipt
        end
        put :credits_checkout, on: :member
      end

      collection do
        get :fallback_create, to: 'projects#create'
      end
      get 'video', on: :collection
      member do
        post :upload_image
        get 'insights'
        get 'posts'
        get 'surveys'
        get 'contributions_report'
        get 'download_reports'
        put 'pay'
        get 'embed'
        get 'video_embed'
        get 'embed_panel'
        get 'send_to_analysis'
        get 'publish'
        get 'validate_publish'
        get 'push_to_online'
      end
    end
    resources :users do
      resources :credit_cards, controller: 'users/credit_cards', only: [:destroy]
      member do
        # get :balance
        post :upload_image
        get :credit_cards
        get :unsubscribe_notifications
        get :credits
        get :settings
        get :billing
        get :reactivate
        post :new_password
      end

      resources :unsubscribes, only: [:create]
      member do
        get 'projects'
        put 'unsubscribe_update'
        put 'update_email'
        put 'update_password'
      end
    end

    get '/terms-of-use' => 'high_voltage/pages#show', id: 'terms_of_use'
    get '/privacy-policy' => 'high_voltage/pages#show', id: 'privacy_policy'
    get '/start' => 'high_voltage/pages#show', id: 'start'
    get '/jobs' => 'high_voltage/pages#show', id: 'jobs'
    get '/hello' => redirect('/start')
    get '/press' => 'high_voltage/pages#show', id: 'press'
    get '/assets' => 'high_voltage/pages#show', id: 'assets'
    get '/guides' => redirect('http://fazum.catarse.me/guia-financiamento-coletivo')
    get '/new-admin' => 'high_voltage/pages#show', id: 'new_admin'
    get '/explore' => 'high_voltage/pages#show', id: 'explore'
    get '/team' => 'high_voltage/pages#show', id: 'team'
    get '/flex' => redirect('http://crowdfunding.catarse.me')
    get '/projects_dashboard' => 'high_voltage/pages#show', id: 'projects_dashboard'

    # Root path should be after channel constraints
    root to: 'projects#index'

    namespace :reports do
      resources :contribution_reports_for_project_owners, only: [:index]
    end

    # Feedback form
    resources :feedbacks, only: [:create]

    namespace :admin do
      resources :balance_transfers do
        collection do
          post 'batch_approve'
          post 'batch_manual'
          post 'batch_reject'
        end
      end

      resources :projects, :flexible_projects, controller: 'projects', only: %i[index update destroy] do
        member do
          put 'approve'
          put 'push_to_online'
          put 'reject'
          put 'push_to_draft'
          put 'push_to_trash'
        end
      end

      resources :financials, only: [:index]

      resources :contributions, only: [] do
        member do
          put 'gateway_refund'
        end
      end

      namespace :reports do
        resources :contribution_reports, only: [:index]
      end
    end

    resource :api_token, only: [:show]

    get '/:permalink' => 'projects#show', as: :project_by_slug
  end
end

app/views/catarse_bootstrap/layouts/_embed.html.slim
doctype 5
html lang="#{I18n.locale}" xmlns:fb="http://ogp.me/ns/fb#"
  head
    meta charset='utf-8'
    title = (yield :page_title if content_for?(:page_title)) || CatarseSettings[:company_name]
    = stylesheet_link_tag 'catarse_bootstrap/catarse'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'
    = csrf_meta_tag

    / Embeds shouls never be indexed
    meta name="robots" content="noindex, nofollow"
    link rel='shortcut icon' href="/images/favicon.ico"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = render_google_analytics_script
  body#catarse_bootstrap[data-controller-name=controller_name data-action=action_name data-user="#{current_user.try(:to_analytics_json)}"]
    = yield

app/views/catarse_bootstrap/layouts/_facebook_like.html.slim
.facebook
  .fb-like data-layout="button_count" data-title= (defined?(title) ? title : '') data-href=(defined?(href) ? href : "#{CatarseSettings[:facebook_url]}") data-send="false" data-colorscheme=(defined?(colorscheme) ? colorscheme : "light") data-width="#{defined?(width) ? width : '260'}" data-show-faces="false"

app/views/catarse_bootstrap/layouts/_facebook_pixel.html.slim
javascript:
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '#{CatarseSettings[:facebook_pixel_id]}');
  fbq('track', "PageView");
noscript
  img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=#{CatarseSettings[:facebook_pixel_id]}&ev=PageView&noscript=1"

app/views/catarse_bootstrap/layouts/_facebook_sdk.html.slim
#fb-root
javascript:
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '#{CatarseSettings['facebook_app_id']}', // App ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true,  // parse XFBML
      version    : 'v2.0'
    });

  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/#{t('facebook_locale')}/sdk.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));

app/views/catarse_bootstrap/layouts/_facebook_share.html.slim
.fb-share-button data-href=(defined?(href) ? href : "#{CatarseSettings[:facebook_url]}") data-layout="button_count"

app/views/catarse_bootstrap/layouts/_facebook_share_mobile.html.slim
= link_to "http://www.facebook.com/sharer/sharer.php?u=#{url}&title=#{title}", class: 'btn btn-medium btn-fb' do
  = image_tag 'catarse_bootstrap/facebook-xxl.png', class: 'icon-share-mobile'
  = t('projects.show.share')

app/views/catarse_bootstrap/layouts/_global_alert.html.slim
- if !@project && controller_name != 'donations'
	#global-alert.alert-top.w-hidden
	  a#close-global-alert.w-inline-block.u-right.fa.fa-times.link-hidden href="#" 
	  .u-text-center.w-container
	    .fontsize-base
	      | Preparamos um vídeo especial explicando o financiamento coletivo. &nbsp; &nbsp;
	      a.btn.btn-inline.btn-small href="http://crowdfunding.catarse.me/paratodos?ref=ctrse_alert_top"  Veja aqui

  

app/views/catarse_bootstrap/layouts/_google_translate.slim
javascript:
	function googleTranslateElementInit() {
    new google.translate.TranslateElement({pageLanguage: 'pt', includedLanguages: 'de,en,es,fr,it', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL, autoDisplay: false, gaTrack: true, gaId: 'UA-51266701-1'}, 'google_translate_element');
  }

script(async src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit")

app/views/catarse_bootstrap/layouts/_mailer_styles.html.erb
<style type='text/css'>
  .button {
    color:#ffffff;
    display:inline-block;
    font-family:'Helvetica',Arial,sans-serif;
    width:auto;
    white-space:nowrap;
    min-height:32px;
    margin:5px 5px 0 0;
    padding:0 22px;
    text-decoration:none;
    text-align:center;
    font-weight:bold;
    font-style:normal;
    font-size:15px;
    line-height:32px;
    border:0;
    border-radius:4px;
    vertical-align:top;
    background-color:#00cb33
  }
  table{
    table-layout: fixed; 
  }
  img{
    max-width: 100%;
  }
</style>

app/views/catarse_bootstrap/layouts/_new_zendesk.html.slim
script(async src="//assets.zendesk.com/external/zenbox/v2.6/zenbox.js" type="text/javascript")
style media="screen, projection" type="text/css"
  | @import url(//assets.zendesk.com/external/zenbox/v2.6/zenbox.css);
javascript:
  if (typeof(Zenbox) !== "undefined") {
    Zenbox.init({
      dropboxID:   "#{CatarseSettings[:zendesk_dropbox_id]}",
      url:         "#{CatarseSettings[:zendesk_url]}",
      tabTooltip:  "Suporte",
      tabImageURL: "https://assets.zendesk.com/external/zenbox/images/tab_pt_support.png",
      tabColor:    "black",
      hide_tab:    "true",
      requester_name: "#{current_user ? current_user.name : ''}",
      requester_email: "#{current_user ? current_user.email : ''}",
      tabPosition: "Left"
    });
  }

app/views/catarse_bootstrap/layouts/_optinmonster.html.slim
- if Rails.env.production? && CatarseSettings['optinmonster_id'].present?
  #om-om56f1a1fa870e6-holder
  javascript:
    var om56f1a1fa870e6,om56f1a1fa870e6_poll=function(){var r=0;return function(n,l){clearInterval(r),r=setInterval(n,l)}}();!function(e,t,n){if(e.getElementById(n)){om56f1a1fa870e6_poll(function(){if(window['om_loaded']){if(!om56f1a1fa870e6){om56f1a1fa870e6=new OptinMonsterApp();return om56f1a1fa870e6.init({"s":"#{CatarseSettings['optinmonster_id']}","staging":0,"dev":0,"beta":0});}}},25);return;}var d=false,o=e.createElement(t);o.id=n,o.src="//a.optnmnstr.com/app/js/api.min.js",o.onload=o.onreadystatechange=function(){if(!d){if(!this.readyState||this.readyState==="loaded"||this.readyState==="complete"){try{d=om_loaded=true;om56f1a1fa870e6=new OptinMonsterApp();om56f1a1fa870e6.init({"s":"#{CatarseSettings['optinmonster_id']}","staging":0,"dev":0,"beta":0});o.onload=o.onreadystatechange=null;}catch(t){}}}};(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(o)}(document,"script","omapi-script");

app/views/catarse_bootstrap/layouts/_twitter_mobile.html.erb
<a href="//twitter.com/share" class="icon-share-mobile" data-title="<%= defined?(title) ? title : '' %>" id="twitter_share_button" data-count="<%= (defined?(count) ? count : 'horizontal') %>" data-via="<%= (defined?(via) ? via : CatarseSettings[:twitter_username]) %>" data-text="<%= (defined?(text) ? text : t('projects.twitter.take_a_look', :name => @project.name) ) %>" data-url="<%= (defined?(url) ? url : request.url) %>"><%=image_tag 'catarse_bootstrap/twitter-256.png'%></a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>

app/views/catarse_bootstrap/layouts/_zendesk_widget.html.slim
- if CatarseSettings[:zendesk_url].present?
  javascript:
    window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(c){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("https://assets.zendesk.com/embeddable_framework/main.js","#{CatarseSettings[:zendesk_url].gsub(/https:\/\//, '')}");

    zE(function() {
      zE.setLocale('#{I18n.locale}');
      zE.identify({
        name: '#{current_user.try(:name)}',
        email: '#{current_user.try(:email)}',
        externalId: '#{current_user.try(:id)}'
      });
    });

app/views/catarse_bootstrap/layouts/catarse_bootstrap.html.slim
doctype 5
html
  head
    title= content_for(:title)
    = auto_discovery_link_tag :atom, projects_url(format: :atom)
    = auto_discovery_link_tag :rss, projects_url(format: :rss)
    = stylesheet_link_tag 'catarse_bootstrap/fonts'
    = stylesheet_link_tag 'catarse_bootstrap/catarse'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'
    = content_for(:stylesheets)
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"
    meta name="root-url" content=root_url
    meta#api-host name="api-host" content=CatarseSettings[:api_host]
    meta#rd-token name="rd-token" content=CatarseSettings[:rd_token]
    - if CatarseSettings[:simility_customer_id].present?
      meta#simility-customer name="simility-customer" content=CatarseSettings[:simility_customer_id]
    meta#newsletter-url name='newsletter-url' content=subscribe_newsletter_url
    - if content_for? :meta_tags
      /project specific meta tags
      = yield :meta_tags
    - else
      /meta tags for the whole site
      meta name="description"         content=t('site.description')
      meta name="keywords"            content=t('site.keywords')
      meta name="google-site-verification"  content=CatarseSettings[:google_verification_code]

      meta property="og:title"        content=t('site.title')
      meta property="og:type"         content=:cause
      meta property="og:image"        content=CatarseSettings[:company_logo]
      meta property="og:site_name"    content=CatarseSettings[:company_name]
      meta property="fb:app_id"       content=CatarseSettings[:facebook_app_id]
      meta property="og:description"  content=(t('projects.index_header.title') + '. ' +  t('projects.index_header.subtitle'))
      meta property="og:url"          content=root_url(locale:'')
    - if request.subdomain.include? "beta"
      meta name="robots" content="noindex, nofollow"
    = render_google_analytics_script
    - if CatarseSettings[:sentry_dsn].present? && !Rails.env.development?
      = javascript_include_tag "https://cdn.ravenjs.com/3.14.2/raven.min.js"
      javascript:
        Raven.config("#{CatarseSettings[:sentry_public_dsn]}").install()
    - if content_for? :tracker_snippet_html
      = yield :tracker_snippet_html
    - if Rails.env.production?
      = render 'layouts/facebook_pixel'
  body#catarse_bootstrap[data-controller-name=controller_name data-action=action_name data-settings="#{public_settings}" data-user="#{current_user.try(:to_analytics_json)}" data-referral="#{session[:referral_link]}" data-id=params[:id] data-blog="#{(Blog.fetch_last_posts rescue [])[0..2].to_json if is_projects_home?}" data-mobile=browser.mobile?.to_s itemscope itemtype="http://schema.org/WebPage" class="#{content_for :body_class}"]
    - if CatarseSettings[:rd_token]
      script(async src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/09f3866f-4c20-40a4-bfb8-68c2310d3964-loader.js" type="text/javascript")
    = render 'layouts/new_zendesk'
    = render 'layouts/zendesk_widget'
    = render_facebook_sdk
    = render 'layouts/flash' if notice.present?
    = yield

  = javascript_include_tag :analytics
  - if CatarseSettings[:simility_customer_id].present?
    = javascript_include_tag "https://cdn.simility.com/b.js", data: { autoexecute: false }
  - if content_for? :application_js
    = yield :application_js
  - else
    = javascript_include_tag :application

  - if content_for? :js
    /page specific JS files
    = yield :js
  - if Rails.env.production?
    = render 'layouts/optinmonster'
  = render 'layouts/google_translate'
  - if content_for? :js_after
    /page specific JS files
    = yield :js_after